//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP_Article_Web_Test
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Net;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using Newtonsoft.Json;

    public class AripaevTeemaveebide_ArtikliteVanuseTest : WebTest
    {

        public AripaevTeemaveebide_ArtikliteVanuseTest()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht");
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.High))
            {
                ValidationRuleFindText validationRule3 = new ValidationRuleFindText();
                validationRule3.FindText = "VORMISTA TELLIMUS KOHE JA SAAD:";
                validationRule3.IgnoreCase = false;
                validationRule3.UseRegularExpression = false;
                validationRule3.PassIfTextFound = true;
                request1.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule3.Validate);
            }
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://imgsrv.kuldnebors.ee/dynamic/flickers8/raamatupidaja32080.html");
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request3.Method = "OPTIONS";
            request3.QueryStringParameters.Add("limit", "15", false, false);
            request3.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request3.QueryStringParameters.Add("page", "1", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request4.Method = "OPTIONS";
            request4.QueryStringParameters.Add("limit", "15", false, false);
            request4.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request4.QueryStringParameters.Add("page", "1", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/seminar");
            request5.Method = "OPTIONS";
            request5.QueryStringParameters.Add("limit", "15", false, false);
            request5.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request5.QueryStringParameters.Add("page", "1", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://listapi.aripaev.ee/v1/tag/project/tarkvara");
            request6.Method = "OPTIONS";
            request6.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request6.QueryStringParameters.Add("limit", "6", false, false);
            request6.QueryStringParameters.Add("page", "1", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/jobs");
            request7.Method = "OPTIONS";
            request7.QueryStringParameters.Add("limit", "15", false, false);
            request7.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request7.QueryStringParameters.Add("page", "1", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/magazine");
            request8.Method = "OPTIONS";
            request8.QueryStringParameters.Add("limit", "15", false, false);
            request8.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request8.QueryStringParameters.Add("page", "1", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request9.Method = "OPTIONS";
            request9.QueryStringParameters.Add("limit", "15", false, false);
            request9.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request9.QueryStringParameters.Add("page", "1", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://eventsapi.aripaev.ee/v1/events");
            request10.Method = "OPTIONS";
            request10.QueryStringParameters.Add("type", "event", false, false);
            request10.QueryStringParameters.Add("past_events", "false", false, false);
            request10.QueryStringParameters.Add("limit", "20", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/cm");
            request11.Method = "OPTIONS";
            request11.QueryStringParameters.Add("limit", "15", false, false);
            request11.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request11.QueryStringParameters.Add("page", "1", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://listapi.aripaev.ee/v1/most-viewed");
            request12.Method = "OPTIONS";
            request12.QueryStringParameters.Add("period", "1_week", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://listapi.aripaev.ee/v1/sections");
            request13.Method = "OPTIONS";
            request13.QueryStringParameters.Add("limit", "2", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://connect.facebook.net/signals/config/444381375738055");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            request14.QueryStringParameters.Add("v", "2.8.50", false, false);
            request14.QueryStringParameters.Add("r", "stable", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://aripaee.adocean.pl/files/x/nnc/notsovx/rphobtnmnd/index.html");
            request15.ThinkTime = 2;
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://marketingapi.aripaev.ee/api/campaign");
            request16.ThinkTime = 4;
            request16.Method = "POST";
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            StringHttpBody request16Body = new StringHttpBody();
            request16Body.ContentType = "application/json";
            request16Body.InsertByteOrderMark = false;
            request16Body.BodyString = "{\"userId\":\"wrMYr7VHWUgXmm9D+7a9NzKIDNQ=\",\"isLoggedIn\":false,\"isAuthorized\":false," +
                "\"isLocked\":true,\"inArticle\":true,\"articleUuid\":\"ab51c06c-9034-4c51-b487-e0da802d" +
                "e03a\"}";
            request16.Body = request16Body;
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://accessapi.aripaev.ee/v1/ip/raamatupidaja");
            request17.Method = "OPTIONS";
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://accessapi.aripaev.ee/v1/ip/raamatupidaja");
            request18.Headers.Add(new WebTestRequestHeader("content-type", "application/json"));
            request18.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://login.aripaev.ee/OAuth/Authorize");
            request19.ExpectedResponseUrl = @"https://login.aripaev.ee/Account/Login?ReturnUrl=%2fOAuth%2fAuthorize%3fclient_id%3draamatupidaja%26response_type%3dcode%26scope%3d%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht&client_id=raamatupidaja&response_type=code&scope=%2FUserDataService%2Fjson%2FProfile%20%2FUserDataService%2Fjson%2FPermissions%20%2FUserDataService%2Fjson%2FOrders&redirect_uri=https%3A%2F%2Faccessapi.aripaev.ee%2Fv1%2Flogin%2Fraamatupidaja%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.raamatupidaja.ee%252Fuudised%252F2019%252F05%252F20%252Fmoodikute-sarav-liider-pohjataht";
            request19.QueryStringParameters.Add("client_id", "raamatupidaja", false, false);
            request19.QueryStringParameters.Add("response_type", "code", false, false);
            request19.QueryStringParameters.Add("scope", "%2FUserDataService%2Fjson%2FProfile%20%2FUserDataService%2Fjson%2FPermissions%20%" +
                    "2FUserDataService%2Fjson%2FOrders", false, false);
            request19.QueryStringParameters.Add("redirect_uri", "https%3A%2F%2Faccessapi.aripaev.ee%2Fv1%2Flogin%2Fraamatupidaja%3Fredirect_uri%3D" +
                    "https%253A%252F%252Fwww.raamatupidaja.ee%252Fuudised%252F2019%252F05%252F20%252F" +
                    "moodikute-sarav-liider-pohjataht", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://login.aripaev.ee/Account/Login");
            request20.Method = "POST";
            request20.ExpectedResponseUrl = @"https://login.aripaev.ee/global-login?continueUrl=%2FOAuth%2FAuthorize%3Fclient_id%3Draamatupidaja%26response_type%3Dcode%26scope%3D%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3Dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht";
            request20.Headers.Add(new WebTestRequestHeader("Referer", @"https://login.aripaev.ee/Account/Login?ReturnUrl=%2fOAuth%2fAuthorize%3fclient_id%3draamatupidaja%26response_type%3dcode%26scope%3d%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht&client_id=raamatupidaja&response_type=code&scope=%2FUserDataService%2Fjson%2FProfile%20%2FUserDataService%2Fjson%2FPermissions%20%2FUserDataService%2Fjson%2FOrders&redirect_uri=https%3A%2F%2Faccessapi.aripaev.ee%2Fv1%2Flogin%2Fraamatupidaja%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.raamatupidaja.ee%252Fuudised%252F2019%252F05%252F20%252Fmoodikute-sarav-liider-pohjataht"));
            request20.QueryStringParameters.Add("ReturnUrl", @"%2fOAuth%2fAuthorize%3fclient_id%3draamatupidaja%26response_type%3dcode%26scope%3d%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht", false, false);
            request20.QueryStringParameters.Add("client_id", "raamatupidaja", false, false);
            request20.QueryStringParameters.Add("response_type", "code", false, false);
            request20.QueryStringParameters.Add("scope", "%2FUserDataService%2Fjson%2FProfile%20%2FUserDataService%2Fjson%2FPermissions%20%" +
                    "2FUserDataService%2Fjson%2FOrders", false, false);
            request20.QueryStringParameters.Add("redirect_uri", "https%3A%2F%2Faccessapi.aripaev.ee%2Fv1%2Flogin%2Fraamatupidaja%3Fredirect_uri%3D" +
                    "https%253A%252F%252Fwww.raamatupidaja.ee%252Fuudised%252F2019%252F05%252F20%252F" +
                    "moodikute-sarav-liider-pohjataht", false, false);
            FormPostHttpBody request20Body = new FormPostHttpBody();
            request20Body.FormPostParameters.Add("Email", "aratyhista@aripaev.ee");
            request20Body.FormPostParameters.Add("password", "4utom44ttest");
            request20Body.FormPostParameters.Add("RememberMe", "true");
            request20.Body = request20Body;
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://pood.aripaev.ee/Sso/GlobalLogin");
            request21.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request21.Headers.Add(new WebTestRequestHeader("Referer", @"https://login.aripaev.ee/global-login?continueUrl=%2FOAuth%2FAuthorize%3Fclient_id%3Draamatupidaja%26response_type%3Dcode%26scope%3D%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3Dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht"));
            request21.QueryStringParameters.Add("ssoId", "92310c01-205d-40f7-a62b-a36f03ce84db", false, false);
            request21.QueryStringParameters.Add("_", "1558612952797", false, false);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://infopank.ee/Sso/GlobalLogin");
            request22.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request22.Headers.Add(new WebTestRequestHeader("Referer", @"https://login.aripaev.ee/global-login?continueUrl=%2FOAuth%2FAuthorize%3Fclient_id%3Draamatupidaja%26response_type%3Dcode%26scope%3D%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3Dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht"));
            request22.QueryStringParameters.Add("ssoId", "92310c01-205d-40f7-a62b-a36f03ce84db", false, false);
            request22.QueryStringParameters.Add("_", "1558612952798", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://login.aripaev.ee/OAuth/Authorize");
            request23.ExpectedResponseUrl = "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht";
            request23.Headers.Add(new WebTestRequestHeader("Referer", @"https://login.aripaev.ee/global-login?continueUrl=%2FOAuth%2FAuthorize%3Fclient_id%3Draamatupidaja%26response_type%3Dcode%26scope%3D%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3Dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht"));
            request23.QueryStringParameters.Add("client_id", "raamatupidaja", false, false);
            request23.QueryStringParameters.Add("response_type", "code", false, false);
            request23.QueryStringParameters.Add("scope", "%2FUserDataService%2Fjson%2FProfile%20%2FUserDataService%2Fjson%2FPermissions%20%" +
                    "2FUserDataService%2Fjson%2FOrders", false, false);
            request23.QueryStringParameters.Add("redirect_uri", "https%3A%2F%2Faccessapi.aripaev.ee%2Fv1%2Flogin%2Fraamatupidaja%3Fredirect_uri%3D" +
                    "https%253A%252F%252Fwww.raamatupidaja.ee%252Fuudised%252F2019%252F05%252F20%252F" +
                    "moodikute-sarav-liider-pohjataht", false, false);
            WebTestRequest request23Dependent1 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request23Dependent1.Method = "OPTIONS";
            request23Dependent1.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent1.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent1.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent1);
            WebTestRequest request23Dependent2 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request23Dependent2.Method = "OPTIONS";
            request23Dependent2.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent2.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent2.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent2);
            WebTestRequest request23Dependent3 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/seminar");
            request23Dependent3.Method = "OPTIONS";
            request23Dependent3.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent3.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent3.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent3);
            WebTestRequest request23Dependent4 = new WebTestRequest("https://listapi.aripaev.ee/v1/tag/project/tarkvara");
            request23Dependent4.Method = "OPTIONS";
            request23Dependent4.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent4.QueryStringParameters.Add("limit", "6", false, false);
            request23Dependent4.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent4);
            WebTestRequest request23Dependent5 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/jobs");
            request23Dependent5.Method = "OPTIONS";
            request23Dependent5.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent5.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent5.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent5);
            WebTestRequest request23Dependent6 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/magazine");
            request23Dependent6.Method = "OPTIONS";
            request23Dependent6.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent6.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent6.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent6);
            WebTestRequest request23Dependent7 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request23Dependent7.Method = "OPTIONS";
            request23Dependent7.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent7.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent7.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent7);
            WebTestRequest request23Dependent8 = new WebTestRequest("https://eventsapi.aripaev.ee/v1/events");
            request23Dependent8.Method = "OPTIONS";
            request23Dependent8.QueryStringParameters.Add("type", "event", false, false);
            request23Dependent8.QueryStringParameters.Add("past_events", "false", false, false);
            request23Dependent8.QueryStringParameters.Add("limit", "20", false, false);
            request23.DependentRequests.Add(request23Dependent8);
            WebTestRequest request23Dependent9 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/cm");
            request23Dependent9.Method = "OPTIONS";
            request23Dependent9.QueryStringParameters.Add("limit", "15", false, false);
            request23Dependent9.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request23Dependent9.QueryStringParameters.Add("page", "1", false, false);
            request23.DependentRequests.Add(request23Dependent9);
            WebTestRequest request23Dependent10 = new WebTestRequest("https://listapi.aripaev.ee/v1/most-viewed");
            request23Dependent10.Method = "OPTIONS";
            request23Dependent10.QueryStringParameters.Add("period", "1_week", false, false);
            request23.DependentRequests.Add(request23Dependent10);
            WebTestRequest request23Dependent11 = new WebTestRequest("https://listapi.aripaev.ee/v1/sections");
            request23Dependent11.Method = "OPTIONS";
            request23Dependent11.QueryStringParameters.Add("limit", "2", false, false);
            request23.DependentRequests.Add(request23Dependent11);
            WebTestRequest request23Dependent12 = new WebTestRequest("https://connect.facebook.net/signals/config/444381375738055");
            request23Dependent12.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            request23Dependent12.QueryStringParameters.Add("v", "2.8.50", false, false);
            request23Dependent12.QueryStringParameters.Add("r", "stable", false, false);
            request23.DependentRequests.Add(request23Dependent12);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht");
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://login.aripaev.ee/global-logout?continueUrl=https%3A%2F%2Fwww.raamatupidaj" +
                        "a.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-liider-pohjataht"));
            WebTestRequest request24Dependent1 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request24Dependent1.Method = "OPTIONS";
            request24Dependent1.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent1.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent1.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent1);
            WebTestRequest request24Dependent2 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request24Dependent2.Method = "OPTIONS";
            request24Dependent2.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent2.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent2.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent2);
            WebTestRequest request24Dependent3 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/seminar");
            request24Dependent3.Method = "OPTIONS";
            request24Dependent3.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent3.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent3.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent3);
            WebTestRequest request24Dependent4 = new WebTestRequest("https://listapi.aripaev.ee/v1/tag/project/tarkvara");
            request24Dependent4.Method = "OPTIONS";
            request24Dependent4.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent4.QueryStringParameters.Add("limit", "6", false, false);
            request24Dependent4.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent4);
            WebTestRequest request24Dependent5 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/jobs");
            request24Dependent5.Method = "OPTIONS";
            request24Dependent5.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent5.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent5.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent5);
            WebTestRequest request24Dependent6 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/magazine");
            request24Dependent6.Method = "OPTIONS";
            request24Dependent6.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent6.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent6.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent6);
            WebTestRequest request24Dependent7 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request24Dependent7.Method = "OPTIONS";
            request24Dependent7.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent7.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent7.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent7);
            WebTestRequest request24Dependent8 = new WebTestRequest("https://eventsapi.aripaev.ee/v1/events");
            request24Dependent8.Method = "OPTIONS";
            request24Dependent8.QueryStringParameters.Add("type", "event", false, false);
            request24Dependent8.QueryStringParameters.Add("past_events", "false", false, false);
            request24Dependent8.QueryStringParameters.Add("limit", "20", false, false);
            request24.DependentRequests.Add(request24Dependent8);
            WebTestRequest request24Dependent9 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/cm");
            request24Dependent9.Method = "OPTIONS";
            request24Dependent9.QueryStringParameters.Add("limit", "15", false, false);
            request24Dependent9.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request24Dependent9.QueryStringParameters.Add("page", "1", false, false);
            request24.DependentRequests.Add(request24Dependent9);
            WebTestRequest request24Dependent10 = new WebTestRequest("https://listapi.aripaev.ee/v1/most-viewed");
            request24Dependent10.Method = "OPTIONS";
            request24Dependent10.QueryStringParameters.Add("period", "1_week", false, false);
            request24.DependentRequests.Add(request24Dependent10);
            WebTestRequest request24Dependent11 = new WebTestRequest("https://listapi.aripaev.ee/v1/sections");
            request24Dependent11.Method = "OPTIONS";
            request24Dependent11.QueryStringParameters.Add("limit", "2", false, false);
            request24.DependentRequests.Add(request24Dependent11);
            WebTestRequest request24Dependent12 = new WebTestRequest("https://connect.facebook.net/signals/config/444381375738055");
            request24Dependent12.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            request24Dependent12.QueryStringParameters.Add("v", "2.8.50", false, false);
            request24Dependent12.QueryStringParameters.Add("r", "stable", false, false);
            request24.DependentRequests.Add(request24Dependent12);
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.High))
            {
                ValidationRuleFindText validationRule4 = new ValidationRuleFindText();
                validationRule4.FindText = "kaebus, kaubatagastus, kaubapuudus, hilinemine, valeinfo, valearvestus, puudumine" +
                    ".";
                validationRule4.IgnoreCase = false;
                validationRule4.UseRegularExpression = false;
                validationRule4.PassIfTextFound = true;
                request24.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule4.Validate);
            }
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://www.facebook.com/tr/");
            request25.Method = "POST";
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            FormPostHttpBody request25Body = new FormPostHttpBody();
            request25Body.FormPostParameters.Add("id", "444381375738055");
            request25Body.FormPostParameters.Add("ev", "Microdata");
            request25Body.FormPostParameters.Add("dl", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht");
            request25Body.FormPostParameters.Add("rl", @"https://login.aripaev.ee/global-login?continueUrl=%2FOAuth%2FAuthorize%3Fclient_id%3Draamatupidaja%26response_type%3Dcode%26scope%3D%252FUserDataService%252Fjson%252FProfile%2520%252FUserDataService%252Fjson%252FPermissions%2520%252FUserDataService%252Fjson%252FOrders%26redirect_uri%3Dhttps%253A%252F%252Faccessapi.aripaev.ee%252Fv1%252Flogin%252Fraamatupidaja%253Fredirect_uri%253Dhttps%25253A%25252F%25252Fwww.raamatupidaja.ee%25252Fuudised%25252F2019%25252F05%25252F20%25252Fmoodikute-sarav-liider-pohjataht");
            request25Body.FormPostParameters.Add("if", "false");
            request25Body.FormPostParameters.Add("ts", "1558612962693");
            request25Body.FormPostParameters.Add("cd[DataLayer]", "[]");
            request25Body.FormPostParameters.Add("cd[Meta]", @"{""title"":""Mõõdikute särav liider – Põhjatäht"",""meta:description"":""Mõõdikute särav liider – PõhjatähtTavapärane juhtimisaruandlus keskendub finantsaruannetele: kasumiaruandele, bilansile ja rahavoogude aruandele. Finantsaruanded omandavad sisu, kui neid millegagi võrrelda. Mõõdikuid kasutatakse tagasiside saamiseks, et võrrelda saadud tulemust eesmärgiga..""}");
            request25Body.FormPostParameters.Add("cd[OpenGraph]", @"{""og:site_name"":""Äripäev"",""og:title"":""Mõõdikute särav liider – Põhjatäht"",""og:url"":""https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"",""og:description"":""Tavapärane juhtimisaruandlus keskendub finantsaruannetele: kasumiaruandele, bilansile ja rahavoogude aruandele. Finantsaruanded omandavad sisu, kui neid millegagi võrrelda. Mõõdikuid kasutatakse tagasiside saamiseks, et võrrelda saadud tulemust eesmärgiga."",""og:image"":""https://static-img.aripaev.ee/?type=preview&uuid=8612b3fe-9256-5d3f-b5ef-54fc8b6173b1&width=1200&q=85"",""og:image:width"":""1200"",""og:type"":""article"",""og:locale"":""et_EE""}");
            request25Body.FormPostParameters.Add("cd[Schema.org]", "[]");
            request25Body.FormPostParameters.Add("cd[JSON-LD]", "[]");
            request25Body.FormPostParameters.Add("sw", "1920");
            request25Body.FormPostParameters.Add("sh", "1080");
            request25Body.FormPostParameters.Add("v", "2.8.50");
            request25Body.FormPostParameters.Add("r", "stable");
            request25Body.FormPostParameters.Add("ec", "1");
            request25Body.FormPostParameters.Add("o", "14");
            request25Body.FormPostParameters.Add("fbp", "fb.1.1558611821278.1896049725");
            request25Body.FormPostParameters.Add("it", "1558612961841");
            request25Body.FormPostParameters.Add("coo", "false");
            request25Body.FormPostParameters.Add("es", "automatic");
            request25Body.FormPostParameters.Add("rqm", "formPOST");
            request25.Body = request25Body;
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://imgsrv.kuldnebors.ee/dynamic/flickers8/raamatupidaja32080.html");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://aripaee.adocean.pl/files/x/nnc/notsovx/rphobtnmnd/index.html");
            request27.ThinkTime = 2;
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://marketingapi.aripaev.ee/api/campaign");
            request28.ThinkTime = 8;
            request28.Method = "POST";
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            StringHttpBody request28Body = new StringHttpBody();
            request28Body.ContentType = "application/json";
            request28Body.InsertByteOrderMark = false;
            request28Body.BodyString = "{\"userId\":\"92310c01-205d-40f7-a62b-a36f03ce84db\",\"isLoggedIn\":true,\"isAuthorized\"" +
                ":true,\"isLocked\":true,\"inArticle\":true,\"articleUuid\":\"ab51c06c-9034-4c51-b487-e0" +
                "da802de03a\"}";
            request28.Body = request28Body;
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://www.raamatupidaja.ee/api/logout");
            request29.Method = "POST";
            request29.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            StringHttpBody request29Body = new StringHttpBody();
            request29Body.ContentType = "application/json";
            request29Body.InsertByteOrderMark = false;
            request29Body.BodyString = "";
            request29.Body = request29Body;
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://login.aripaev.ee/Account/Logout");
            request30.ExpectedResponseUrl = "https://login.aripaev.ee/global-logout?continueUrl=https%3A%2F%2Fwww.raamatupidaj" +
                "a.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-liider-pohjataht";
            request30.QueryStringParameters.Add("returnUrl", "https%3A%2F%2Fwww.raamatupidaja.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-l" +
                    "iider-pohjataht", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://pood.aripaev.ee/Sso/GlobalLogout");
            request31.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request31.Headers.Add(new WebTestRequestHeader("Referer", "https://login.aripaev.ee/global-logout?continueUrl=https%3A%2F%2Fwww.raamatupidaj" +
                        "a.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-liider-pohjataht"));
            request31.QueryStringParameters.Add("_", "1558612975118", false, false);
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://infopank.ee/Sso/GlobalLogout");
            request32.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request32.Headers.Add(new WebTestRequestHeader("Referer", "https://login.aripaev.ee/global-logout?continueUrl=https%3A%2F%2Fwww.raamatupidaj" +
                        "a.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-liider-pohjataht"));
            request32.QueryStringParameters.Add("_", "1558612975119", false, false);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht");
            request33.Headers.Add(new WebTestRequestHeader("Referer", "https://login.aripaev.ee/global-logout?continueUrl=https%3A%2F%2Fwww.raamatupidaj" +
                        "a.ee%2Fuudised%2F2019%2F05%2F20%2Fmoodikute-sarav-liider-pohjataht"));
            WebTestRequest request33Dependent1 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request33Dependent1.Method = "OPTIONS";
            request33Dependent1.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent1.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent1.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent1);
            WebTestRequest request33Dependent2 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request33Dependent2.Method = "OPTIONS";
            request33Dependent2.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent2.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent2.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent2);
            WebTestRequest request33Dependent3 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/seminar");
            request33Dependent3.Method = "OPTIONS";
            request33Dependent3.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent3.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent3.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent3);
            WebTestRequest request33Dependent4 = new WebTestRequest("https://listapi.aripaev.ee/v1/tag/project/tarkvara");
            request33Dependent4.Method = "OPTIONS";
            request33Dependent4.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent4.QueryStringParameters.Add("limit", "6", false, false);
            request33Dependent4.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent4);
            WebTestRequest request33Dependent5 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/jobs");
            request33Dependent5.Method = "OPTIONS";
            request33Dependent5.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent5.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent5.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent5);
            WebTestRequest request33Dependent6 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/magazine");
            request33Dependent6.Method = "OPTIONS";
            request33Dependent6.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent6.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent6.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent6);
            WebTestRequest request33Dependent7 = new WebTestRequest("https://listapi.aripaev.ee/v1/category");
            request33Dependent7.Method = "OPTIONS";
            request33Dependent7.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent7.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent7.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent7);
            WebTestRequest request33Dependent8 = new WebTestRequest("https://eventsapi.aripaev.ee/v1/events");
            request33Dependent8.Method = "OPTIONS";
            request33Dependent8.QueryStringParameters.Add("type", "event", false, false);
            request33Dependent8.QueryStringParameters.Add("past_events", "false", false, false);
            request33Dependent8.QueryStringParameters.Add("limit", "20", false, false);
            request33.DependentRequests.Add(request33Dependent8);
            WebTestRequest request33Dependent9 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/cm");
            request33Dependent9.Method = "OPTIONS";
            request33Dependent9.QueryStringParameters.Add("limit", "15", false, false);
            request33Dependent9.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request33Dependent9.QueryStringParameters.Add("page", "1", false, false);
            request33.DependentRequests.Add(request33Dependent9);
            WebTestRequest request33Dependent10 = new WebTestRequest("https://listapi.aripaev.ee/v1/most-viewed");
            request33Dependent10.Method = "OPTIONS";
            request33Dependent10.QueryStringParameters.Add("period", "1_week", false, false);
            request33.DependentRequests.Add(request33Dependent10);
            WebTestRequest request33Dependent11 = new WebTestRequest("https://listapi.aripaev.ee/v1/sections");
            request33Dependent11.Method = "OPTIONS";
            request33Dependent11.QueryStringParameters.Add("limit", "2", false, false);
            request33.DependentRequests.Add(request33Dependent11);
            WebTestRequest request33Dependent12 = new WebTestRequest("https://connect.facebook.net/signals/config/444381375738055");
            request33Dependent12.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            request33Dependent12.QueryStringParameters.Add("v", "2.8.50", false, false);
            request33Dependent12.QueryStringParameters.Add("r", "stable", false, false);
            request33.DependentRequests.Add(request33Dependent12);
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://imgsrv.kuldnebors.ee/dynamic/flickers8/raamatupidaja32080.html");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://aripaee.adocean.pl/files/x/nnc/notsovx/rphobtnmnd/index.html");
            request35.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://marketingapi.aripaev.ee/api/campaign");
            request36.ThinkTime = 1;
            request36.Method = "POST";
            request36.Headers.Add(new WebTestRequestHeader("Referer", "https://www.raamatupidaja.ee/uudised/2019/05/20/moodikute-sarav-liider-pohjataht"));
            StringHttpBody request36Body = new StringHttpBody();
            request36Body.ContentType = "application/json";
            request36Body.InsertByteOrderMark = false;
            request36Body.BodyString = "{\"userId\":\"EoJfRnHqOUkY+3gQmHjYQj00aKc=\",\"isLoggedIn\":false,\"isAuthorized\":false," +
                "\"isLocked\":true,\"inArticle\":true,\"articleUuid\":\"ab51c06c-9034-4c51-b487-e0da802d" +
                "e03a\"}";
            request36.Body = request36Body;
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("https://www.imelineajalugu.ee/uudised/2019/05/10/kui-eesti-vaed-pihkvas-kaisid");
            WebTestRequest request37Dependent1 = new WebTestRequest("https://listapi.aripaev.ee/v1/category/news");
            request37Dependent1.Method = "OPTIONS";
            request37Dependent1.QueryStringParameters.Add("limit", "11", false, false);
            request37Dependent1.QueryStringParameters.Add("exclude_uuids", "", false, false);
            request37Dependent1.QueryStringParameters.Add("page", "1", false, false);
            request37.DependentRequests.Add(request37Dependent1);
            WebTestRequest request37Dependent2 = new WebTestRequest("https://connect.facebook.net/signals/config/444381375738055");
            request37Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www.imelineajalugu.ee/uudised/2019/05/10/kui-eesti-vaed-pihkvas-kaisid"));
            request37Dependent2.QueryStringParameters.Add("v", "2.8.50", false, false);
            request37Dependent2.QueryStringParameters.Add("r", "stable", false, false);
            request37.DependentRequests.Add(request37Dependent2);
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.High))
            {
                ValidationRuleFindText validationRule5 = new ValidationRuleFindText();
                validationRule5.FindText = "Soomusrongide divisjoni väeosad asusid kaares";
                validationRule5.IgnoreCase = false;
                validationRule5.UseRegularExpression = false;
                validationRule5.PassIfTextFound = true;
                request37.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule5.Validate);
            }
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://marketingapi.aripaev.ee/api/campaign");
            request38.Method = "POST";
            request38.Headers.Add(new WebTestRequestHeader("Referer", "https://www.imelineajalugu.ee/uudised/2019/05/10/kui-eesti-vaed-pihkvas-kaisid"));
            StringHttpBody request38Body = new StringHttpBody();
            request38Body.ContentType = "application/json";
            request38Body.InsertByteOrderMark = false;
            request38Body.BodyString = "{\"userId\":\"B83RJFx7F3znl9lBM9aToePynKE=\",\"isLoggedIn\":false,\"isAuthorized\":true,\"" +
                "isLocked\":false,\"inArticle\":true,\"articleUuid\":\"c7d8e7b9-f283-42a8-a48d-ea4da533" +
                "1c57\"}";
            request38.Body = request38Body;
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("https://listapi.aripaev.ee/v1/most-viewed");
            request39.Headers.Add(new WebTestRequestHeader("X-Channel-Id", "aripaev"));
            request39.QueryStringParameters.Add("period", "1_day", false, false);
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.High))
            {
                ValidationRuleFindText validationRule4 = new ValidationRuleFindText();
                validationRule4.FindText = "uuid";
                validationRule4.IgnoreCase = false;
                validationRule4.UseRegularExpression = false;
                validationRule4.PassIfTextFound = true;
                request39.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule4.Validate);

                // Custom checks
                //Check aripaev most viewed
                var mostViewedUrl = new Uri("https://listapi.aripaev.ee/v1/most-viewed?period=1_day");
                HttpWebRequest getRequest = (HttpWebRequest)WebRequest.Create(mostViewedUrl);
                getRequest.Method = WebRequestMethods.Http.Get;
                getRequest.ContentType = "application/json";
                getRequest.Headers.Add("X-Channel-Id", "aripaev");
                using (HttpWebResponse getResponse = (HttpWebResponse)getRequest.GetResponse())
                using (StreamReader streamReader = new StreamReader(getResponse.GetResponseStream(), Encoding.UTF8))
                {
                    string responseString = streamReader.ReadToEnd();
                    List<Article> articles = JsonConvert.DeserializeObject<List<Article>>(responseString);
                    bool containsNewArticle = false;

                    for (int i = 0; i < 8; i++)
                    {
                        Article article = articles[i];
                        if (DateTime.Parse(article.Date).AddDays(2) > DateTime.Now)
                        {
                            containsNewArticle = true;
                            break;
                        }
                    }

                    if (!containsNewArticle)
                    {
                        //Kinda hack, if the date check failed, send findtext what will fail 100%.
                        ValidationRuleFindText validateDates = new ValidationRuleFindText();
                        validateDates.FindText = "All the articles @ aripaev.ee most viewed are older than 2 days from now!";
                        validateDates.IgnoreCase = false;
                        validateDates.UseRegularExpression = false;
                        validateDates.PassIfTextFound = true;
                        request39.ValidateResponse += new EventHandler<ValidationEventArgs>(validateDates.Validate);
                    }

                }

                //Check DV most viewed
                var mostViewedDVUrl = new Uri("https://listapi.aripaev.ee/v1/most-viewed?period=1_week");
                HttpWebRequest getDVRequest = (HttpWebRequest)WebRequest.Create(mostViewedUrl);
                getDVRequest.Method = WebRequestMethods.Http.Get;
                getDVRequest.ContentType = "application/json";
                getDVRequest.Headers.Add("X-Channel-Id", "dv");
                using (HttpWebResponse getDVResponse = (HttpWebResponse)getDVRequest.GetResponse())
                using (StreamReader streamReader = new StreamReader(getDVResponse.GetResponseStream(), Encoding.UTF8))
                {
                    string responseString = streamReader.ReadToEnd();
                    List<Article> articlesDV = JsonConvert.DeserializeObject<List<Article>>(responseString);
                    bool containsNewArticle = false;

                    for (int i = 0; i < 8; i++)
                    {
                        Article article = articlesDV[i];
                        if (DateTime.Parse(article.Date).AddDays(3) > DateTime.Now)
                        {
                            containsNewArticle = true;
                            break;
                        }
                    }

                    if (!containsNewArticle)
                    {
                        //Kinda hack, if the date check failed, send findtext what will fail 100%.
                        ValidationRuleFindText validateDates = new ValidationRuleFindText();
                        validateDates.FindText = "All the articles @ DV.ee most viewed are older than 3 days from now!";
                        validateDates.IgnoreCase = false;
                        validateDates.UseRegularExpression = false;
                        validateDates.PassIfTextFound = true;
                        request39.ValidateResponse += new EventHandler<ValidationEventArgs>(validateDates.Validate);
                    }

                }

                //Check raamatupidaja 35 fresh articles
                var raamatupidajaUrl = new Uri("https://listapi.aripaev.ee/v1/category?limit=35");
                HttpWebRequest raamatupidajaRequest = (HttpWebRequest)WebRequest.Create(raamatupidajaUrl);
                raamatupidajaRequest.Method = WebRequestMethods.Http.Get;
                raamatupidajaRequest.ContentType = "application/json";
                raamatupidajaRequest.Headers.Add("X-Channel-Id", "raamatupidaja");
                using (HttpWebResponse raamatupidajaResponse = (HttpWebResponse)raamatupidajaRequest.GetResponse())
                using (StreamReader streamReader = new StreamReader(raamatupidajaResponse.GetResponseStream(), Encoding.UTF8))
                {
                    string responseString = streamReader.ReadToEnd();
                    ListArticles articlesRaamatupidaja = JsonConvert.DeserializeObject<ListArticles>(responseString);

                    bool containsNewArticle = false;
                    foreach (Article article in articlesRaamatupidaja.articles)
                    {
                        if (DateTime.Parse(article.Date).AddDays(7) > DateTime.Now)
                        {
                            containsNewArticle = true;
                            break;
                        }
                    }

                    if (!containsNewArticle)
                    {
                        //Kinda hack, if the date check failed, send findtext what will fail 100%.
                        ValidationRuleFindText validateDates = new ValidationRuleFindText();
                        validateDates.FindText = "All the articles @ Raamatupidaja are 7 or more days old!";
                        validateDates.IgnoreCase = false;
                        validateDates.UseRegularExpression = false;
                        validateDates.PassIfTextFound = true;
                        request39.ValidateResponse += new EventHandler<ValidationEventArgs>(validateDates.Validate);
                    }
                }

                //Check Editors choice 4 fresh articles
                var editorsChoiceUrl = new Uri("https://listapi.aripaev.ee/v1/lists/editorschoice");
                HttpWebRequest editorsChoiceRequest = (HttpWebRequest)WebRequest.Create(editorsChoiceUrl);
                editorsChoiceRequest.Method = WebRequestMethods.Http.Get;
                editorsChoiceRequest.ContentType = "application/json";
                editorsChoiceRequest.Headers.Add("X-Channel-Id", "raamatupidaja");
                using (HttpWebResponse editorsChoiceResponse = (HttpWebResponse)editorsChoiceRequest.GetResponse())
                using (StreamReader streamReader = new StreamReader(editorsChoiceResponse.GetResponseStream(), Encoding.UTF8))
                {
                    string responseString = streamReader.ReadToEnd();
                    EditorsChoiseHeadlist editorsChoiceArticles = JsonConvert.DeserializeObject<EditorsChoiseHeadlist>(responseString);

                    bool containsNewArticle = false;
                    foreach (Article article in editorsChoiceArticles.lists[0].articles)
                    {
                        if (DateTime.Parse(article.Date).AddDays(7) > DateTime.Now)
                        {
                            containsNewArticle = true;
                            break;
                        }
                    }

                    if (!containsNewArticle)
                    {
                        //Kinda hack, if the date check failed, send findtext what will fail 100%.
                        ValidationRuleFindText validateDates = new ValidationRuleFindText();
                        validateDates.FindText = "All the articles @ Raamatupidaja editors choice are 7 or more days old!";
                        validateDates.IgnoreCase = false;
                        validateDates.UseRegularExpression = false;
                        validateDates.PassIfTextFound = true;
                        request39.ValidateResponse += new EventHandler<ValidationEventArgs>(validateDates.Validate);
                    }
                }
            }
            yield return request39;
            request39 = null;
        }
    }
    public class Article
    {
        public long Id { get; set; }
        public string Uuid { get; set; }
        public string Link { get; set; }
        public string Date { get; set; }
        public string Headline { get; set; }
    }

    public class ListArticles
    {
        public List<Article> articles { get; set; }

    }

    public class EditorsChoiceArticles
    {
        public List<Article> articles { get; set; }

    }

    public class EditorsChoiseHeadlist
    {
        public List<EditorsChoiceArticles> lists { get; set; }
    }
}
